# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a6a018e03cad791caba58d2b45f2ac12bcb6a29475c6b331b6ccbf2447db3fb59dc7e0ef306783c0d4aca62b3d3cbeeecd917e3a4e1a617443a0113a77e3a75

test:
  secret_key_base: ce985174944a341f45d935370ac20fab35b098d7826a5404589837883e08608159287bd0c44706d0a10c91bf79fa3fb0a47b8379bd85259ba96e71facc932fd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
